#pragma once


#define AUTO_SHIFT_TIMEOUT 250
#define NO_AUTO_SHIFT_SPECIAL

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define TAPPING_TOGGLE 2

#define SENTENCE_CASE_TIMEOUT 2000
#define DYNAMIC_MACRO_NO_NESTING

#define MOUSEKEY_INERTIA

#define ENABLE_RGB_MATRIX_STARLIGHT
#define ENABLE_RGB_MATRIX_RIVERFLOW
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_RIVERFLOW
#define RGB_MATRIX_DEFAULT_HUE 191

#define NO_MUSIC_MODE

