#pragma once

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define AUTO_SHIFT_TIMEOUT 250
#define NO_AUTO_SHIFT_SPECIAL

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define TAPPING_TOGGLE 2
#define ONESHOT_TAP_TOGGLE 2

#define SENTENCE_CASE_TIMEOUT 2000
#define DYNAMIC_MACRO_NO_NESTING
#define DYNAMIC_MACRO_USER_CALL

#define ENABLE_RGB_MATRIX_HUE_BREATHING
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_HUE_BREATHING
#define RGB_MATRIX_DEFAULT_HUE 191
